-d C:\Users\Admin\OneDrive\Desktop\Intern_Docs\intern\fpga_gao_project\impl\gwsynthesis\fpga_gao_project.vg
-p GW1NSR-4C-QFN48P-7
-pn GW1NSR-LV4CQN48PC7/I6
-cst C:\Users\Admin\OneDrive\Desktop\Intern_Docs\intern\fpga_gao_project\src\top_hdl.cst
-cfg C:\Users\Admin\OneDrive\Desktop\Intern_Docs\intern\fpga_gao_project\impl\pnr\device.cfg
-sdc C:\Users\Admin\OneDrive\Desktop\Intern_Docs\intern\fpga_gao_project\src\top_hdl.sdc
-gao_crc 1011000111011101
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
-rtl_gao
